### Initializations

In [54]:
import json
import pandas as pd
import requests

from pprint import pprint

base_url = "https://clinicaltrials.gov/api/v2/studies"
page_size = 10
request_timeout_seconds = 30

### First request

In [6]:
params = {
    "pageSize": page_size,
    "format": "json",
}

response = requests.get(
    base_url,
    params=params,
    timeout=request_timeout_seconds,
)

response.raise_for_status()

data = response.json()

### Inspect the general response

In [35]:
data.keys()

dict_keys(['studies', 'nextPageToken'])

In [37]:
len(data["studies"])

10

In [42]:
first_study = data["studies"][0]

type(first_study)

dict

In [43]:
first_study.keys()

dict_keys(['protocolSection', 'derivedSection', 'hasResults'])

In [47]:
print(json.dumps(first_study, indent=2))

{
  "protocolSection": {
    "identificationModule": {
      "nctId": "NCT00830635",
      "orgStudyIdInfo": {
        "id": "08-0498"
      },
      "secondaryIdInfos": [
        {
          "id": "AMCCRC-08-0498"
        }
      ],
      "organization": {
        "fullName": "University of Colorado, Denver",
        "class": "OTHER"
      },
      "briefTitle": "Multimedia Educational Program for Patients With Early-Stage Prostate Cancer or Breast Cancer",
      "officialTitle": "Cancer Information Service Research Consortium: Years 2006-2011 Program Narrative and Overview"
    },
    "statusModule": {
      "statusVerifiedDate": "2015-06",
      "overallStatus": "COMPLETED",
      "expandedAccessInfo": {
        "hasExpandedAccess": false
      },
      "startDateStruct": {
        "date": "2008-09"
      },
      "primaryCompletionDateStruct": {
        "date": "2013-04",
        "type": "ACTUAL"
      },
      "completionDateStruct": {
        "date": "2013-12",
        "type": "ACTUAL"
      },
      "studyFirstSubmitDate": "2009-01-27",
      "studyFirstSubmitQcDate": "2009-01-27",
      "studyFirstPostDateStruct": {
        "date": "2009-01-28",
        "type": "ESTIMATED"
      },
      "lastUpdateSubmitDate": "2015-06-12",
      "lastUpdatePostDateStruct": {
        "date": "2015-06-16",
        "type": "ESTIMATED"
      }
    },
    "sponsorCollaboratorsModule": {
      "responsibleParty": {
        "type": "SPONSOR"
      },
      "leadSponsor": {
        "name": "University of Colorado, Denver",
        "class": "OTHER"
      },
      "collaborators": [
        {
          "name": "National Cancer Institute (NCI)",
          "class": "NIH"
        }
      ]
    },
    "oversightModule": {
      "oversightHasDmc": false
    },
    "descriptionModule": {
      "briefSummary": "RATIONALE: A multimedia educational program may help patients with newly diagnosed prostate cancer and breast cancer reduce distress, make informed treatment decisions, and improve quality of life.\n\nPURPOSE: This randomized clinical trial is studying how well a multimedia educational program works in patients with early-stage prostate cancer or breast cancer.",
      "detailedDescription": "OBJECTIVES:\n\nPrimary\n\n* Determine whether an innovative multimedia educational program will help newly diagnosed prostate (project 1) and breast (project 2) cancer patients prepare for their journey as cancer patients, promote informed treatment decision-making and reduce cancer-specific distress, and among breast cancer patients at re-entry, facilitate an informed re-entry transition to cancer survivorship and reduce cancer-specific distress (project 3).\n* Determine whether having Cancer Information Service (CIS) Information Specialists make a scheduled telephone callback to callers in project 3 will augment and support use of the CIS Research Consortium (CISRC) multimedia educational programs and further enhance the study outcomes examined in this program of research.\n* Determine whether the hypothesized mediational variables account for significant intervention effects in each of the three component projects.\n* Examine potential moderator variables to assess potential differences in intervention efficacy by selected subgroups (e.g., age, education) within each component project.\n* Conduct an in-depth tracking study of utilization patterns for a detailed description of different patterns of use, as well as elucidating those components or modules within the program that had differential utilization by participants.\n* Assist the CIS and other similar cancer information systems in disseminating one or more of the CISRC interventions should they prove effective in this program of research.\n\nSecondary\n\n* Conduct secondary analyses across projects (i.e., perceived need for and benefit from the CISRC interventions and intervention efficacy across three high priority cancer patient populations) that will be made possible by the use of a common theoretical framework, the same or similar intervention and research design across projects, and a common set of endpoints.\n\nOUTLINE: This is a multicenter study.\n\nPatients are assessed by demographic questions and a baseline interview conducted by Cancer Information Service (CIS) Information Specialists.\n\nPatients are randomized to 1 of 3 intervention groups:\n\n* Group 1: Patients receive a mailing containing standard CIS print materials. In project 1, patients receive \" Treatment Choices for Men with Early-Stage Prostate Cancer\" and \"What You Need to Know About Prostate Cancer\". In project 2, patients receive \"What You Need to Know About Breast Cancer\" and \"Surgery Choices for Women with Early-Stage Breast Cancer\". In project 3, patients receive \"Facing Forward: Life After Cancer Treatment\" and \"What You Need to Know About Breast Cancer\".\n* Group 2: Patients receive mailings appropriate to their project as in group 1. Patients also receive the multimedia program via the Internet or CD-ROM.\n* Group 3: In project 3 only, patients receive mailings appropriate to their project as in group 1 and the multimedia program as in group 2. Patients also receive a CIS callback intervention at 10-14 days from trained Information Specialists from the CIS.\n\nAfter completion of study therapy, patients are followed at 2 and 9 months."
    },
    "conditionsModule": {
      "conditions": [
        "Breast Cancer",
        "Depression",
        "Long-term Effects of Cancer Treatment",
        "Prostate Cancer",
        "Psychosocial Effects of Cancer and Its Treatment"
      ],
      "keywords": [
        "long-term effects of cancer treatment",
        "psychosocial effects of cancer and its treatment",
        "depression",
        "stage IA breast cancer",
        "stage IB breast cancer",
        "stage II breast cancer",
        "stage I prostate cancer",
        "stage II prostate cancer"
      ]
    },
    "designModule": {
      "studyType": "INTERVENTIONAL",
      "phases": [
        "NA"
      ],
      "designInfo": {
        "allocation": "NA",
        "interventionModel": "SINGLE_GROUP",
        "maskingInfo": {
          "masking": "NONE"
        }
      },
      "enrollmentInfo": {
        "count": 1800,
        "type": "ACTUAL"
      }
    },
    "armsInterventionsModule": {
      "interventions": [
        {
          "type": "OTHER",
          "name": "educational intervention"
        },
        {
          "type": "OTHER",
          "name": "informational intervention"
        },
        {
          "type": "OTHER",
          "name": "internet-based intervention"
        },
        {
          "type": "OTHER",
          "name": "questionnaire administration"
        },
        {
          "type": "OTHER",
          "name": "study of socioeconomic and demographic variables"
        },
        {
          "type": "OTHER",
          "name": "survey administration"
        },
        {
          "type": "PROCEDURE",
          "name": "psychosocial assessment and care"
        },
        {
          "type": "PROCEDURE",
          "name": "quality-of-life assessment"
        }
      ]
    },
    "outcomesModule": {
      "primaryOutcomes": [
        {
          "measure": "Cancer-specific distress"
        },
        {
          "measure": "Emotional quality of life"
        },
        {
          "measure": "Physical functioning"
        },
        {
          "measure": "Interpersonal functioning"
        },
        {
          "measure": "Benefit-finding"
        },
        {
          "measure": "Decisional conflict (projects 1 and 2)"
        },
        {
          "measure": "Regret (projects 1 and 2)"
        },
        {
          "measure": "Fear of recurrence (project 3)"
        },
        {
          "measure": "Practical concerns (project 3)"
        }
      ]
    },
    "eligibilityModule": {
      "eligibilityCriteria": "DISEASE CHARACTERISTICS:\n\n* Patients are diagnosed with 1 of the following:\n\n  * Diagnosis of prostate cancer (project 1)\n\n    * Early-stage disease\n    * Previously untreated disease or treatment status unknown\n  * Diagnosis of breast cancer (projects 2-3)\n\n    * Early-stage disease\n    * No ductal carcinoma in situ or lobular carcinoma in situ\n    * Inflammatory breast cancer allowed (project 2)\n    * Previously untreated disease, receiving concurrent treatment, previously treated disease, or treatment status unknown\n\n      * No more than 30 days since completion of treatment OR no more than 6 months post-treatment (project 3)\n\nPATIENT CHARACTERISTICS:\n\n* Has access to a computer\n* Willing to provide mailing address and telephone number\n* Must be active information-seekers who have already called the CIS\n* Understands English\n\nPRIOR CONCURRENT THERAPY:\n\n* See Disease Characteristics",
      "healthyVolunteers": false,
      "sex": "ALL",
      "stdAges": [
        "CHILD",
        "ADULT",
        "OLDER_ADULT"
      ]
    },
    "contactsLocationsModule": {
      "overallOfficials": [
        {
          "name": "Alfred Marcus, PhD",
          "affiliation": "AMC Cancer Research Center",
          "role": "PRINCIPAL_INVESTIGATOR"
        }
      ],
      "locations": [
        {
          "facility": "University of Miami Sylvester Comprehensive Cancer Center - Miami",
          "city": "Miami",
          "state": "Florida",
          "zip": "33136",
          "country": "United States",
          "geoPoint": {
            "lat": 25.77427,
            "lon": -80.19366
          }
        },
        {
          "facility": "Memorial Sloan-Kettering Cancer Center",
          "city": "New York",
          "state": "New York",
          "zip": "10021",
          "country": "United States",
          "geoPoint": {
            "lat": 40.71427,
            "lon": -74.00597
          }
        },
        {
          "facility": "Fred Hutchinson Cancer Research Center",
          "city": "Seattle",
          "state": "Washington",
          "zip": "98109-1024",
          "country": "United States",
          "geoPoint": {
            "lat": 47.60621,
            "lon": -122.33207
          }
        }
      ]
    }
  },
  "derivedSection": {
    "miscInfoModule": {
      "versionHolder": "2026-07-10"
    },
    "conditionBrowseModule": {
      "meshes": [
        {
          "id": "D001943",
          "term": "Breast Neoplasms"
        },
        {
          "id": "D003863",
          "term": "Depression"
        },
        {
          "id": "D011471",
          "term": "Prostatic Neoplasms"
        }
      ],
      "ancestors": [
        {
          "id": "D009371",
          "term": "Neoplasms by Site"
        },
        {
          "id": "D009369",
          "term": "Neoplasms"
        },
        {
          "id": "D001941",
          "term": "Breast Diseases"
        },
        {
          "id": "D012871",
          "term": "Skin Diseases"
        },
        {
          "id": "D017437",
          "term": "Skin and Connective Tissue Diseases"
        },
        {
          "id": "D001526",
          "term": "Behavioral Symptoms"
        },
        {
          "id": "D001519",
          "term": "Behavior"
        },
        {
          "id": "D005834",
          "term": "Genital Neoplasms, Male"
        },
        {
          "id": "D014565",
          "term": "Urogenital Neoplasms"
        },
        {
          "id": "D005832",
          "term": "Genital Diseases, Male"
        },
        {
          "id": "D000091662",
          "term": "Genital Diseases"
        },
        {
          "id": "D000091642",
          "term": "Urogenital Diseases"
        },
        {
          "id": "D011469",
          "term": "Prostatic Diseases"
        },
        {
          "id": "D052801",
          "term": "Male Urogenital Diseases"
        }
      ]
    },
    "interventionBrowseModule": {
      "meshes": [
        {
          "id": "D018479",
          "term": "Early Intervention, Educational"
        },
        {
          "id": "D000067250",
          "term": "Psychiatric Rehabilitation"
        }
      ],
      "ancestors": [
        {
          "id": "D002662",
          "term": "Child Health Services"
        },
        {
          "id": "D003153",
          "term": "Community Health Services"
        },
        {
          "id": "D006296",
          "term": "Health Services"
        },
        {
          "id": "D005159",
          "term": "Health Care Facilities Workforce and Services"
        },
        {
          "id": "D011314",
          "term": "Preventive Health Services"
        },
        {
          "id": "D012046",
          "term": "Rehabilitation"
        },
        {
          "id": "D013812",
          "term": "Therapeutics"
        }
      ]
    }
  },
  "hasResults": false
}

### Extract basic fields

In [48]:
protocol_section = first_study.get("protocolSection", {})

identification = protocol_section.get("identificationModule", {})
status = protocol_section.get("statusModule", {})
design = protocol_section.get("designModule", {})
conditions = protocol_section.get("conditionsModule", {})

In [50]:
identification

{'nctId': 'NCT00830635', 'orgStudyIdInfo': {'id': '08-0498'}, 'secondaryIdInfos': [{'id': 'AMCCRC-08-0498'}], 'organization': {'fullName': 'University of Colorado, Denver', 'class': 'OTHER'}, 'briefTitle': 'Multimedia Educational Program for Patients With Early-Stage Prostate Cancer or Breast Cancer', 'officialTitle': 'Cancer Information Service Research Consortium: Years 2006-2011 Program Narrative and Overview'}

In [51]:
study_summary = {
    "nct_id": identification.get("nctId"),
    "brief_title": identification.get("briefTitle"),
    "official_title": identification.get("officialTitle"),
    "overall_status": status.get("overallStatus"),
    "study_type": design.get("studyType"),
    "phases": design.get("phases"),
    "conditions": conditions.get("conditions"),
}

In [52]:
study_summary

{'nct_id': 'NCT00830635', 'brief_title': 'Multimedia Educational Program for Patients With Early-Stage Prostate Cancer or Breast Cancer', 'official_title': 'Cancer Information Service Research Consortium: Years 2006-2011 Program Narrative and Overview', 'overall_status': 'COMPLETED', 'study_type': 'INTERVENTIONAL', 'phases': ['NA'], 'conditions': ['Breast Cancer', 'Depression', 'Long-term Effects of Cancer Treatment', 'Prostate Cancer', 'Psychosocial Effects of Cancer and Its Treatment']}

In [53]:
def extract_study_summary(study: dict) -> dict:
    protocol_section = study.get("protocolSection", {})

    identification = protocol_section.get("identificationModule", {})
    status = protocol_section.get("statusModule", {})
    design = protocol_section.get("designModule", {})
    conditions = protocol_section.get("conditionsModule", {})

    return {
        "nct_id": identification.get("nctId"),
        "brief_title": identification.get("briefTitle"),
        "official_title": identification.get("officialTitle"),
        "overall_status": status.get("overallStatus"),
        "study_type": design.get("studyType"),
        "phases": design.get("phases"),
        "conditions": conditions.get("conditions"),
    }

In [57]:
df_studies = pd.DataFrame(
    extract_study_summary(study)
    for study in data["studies"]
)
df_studies

,nct_id,brief_title,official_title,overall_status,study_type,phases,conditions
0,NCT00830635,Multimedia Educational Program for Patients Wi...,Cancer Information Service Research Consortium...,COMPLETED,INTERVENTIONAL,[NA],"[Breast Cancer, Depression, Long-term Effects ..."
1,NCT06798935,Feasibility and Safety of Additional Injection...,Feasibility and Safety of Additional Injection...,COMPLETED,INTERVENTIONAL,[PHASE2],"[Rectovaginal Fistula, Anovaginal Fistula]"
2,NCT01990235,Improving Advance Care Planning by Preparing D...,Improving Advance Care Planning by Preparing D...,COMPLETED,INTERVENTIONAL,[NA],[Chronic Disease]
3,NCT01419535,Mifepristone Effects on Glucose Intolerance in...,"Effects of the Glucocorticoid Antagonist, Mife...",COMPLETED,INTERVENTIONAL,"[PHASE1, PHASE2]","[Endocrine Disease, Diabetes]"
4,NCT05944835,Validation of Numerical Simulation to Predict ...,Validation of Numerical Simulation to Predict ...,UNKNOWN,OBSERVATIONAL,None,[Surgery]
5,NCT05470335,Nurse-led Sheath Insertion in Cardiac Patients,"Patient Comfort, Success Rate, Procedure Time ...",RECRUITING,INTERVENTIONAL,[NA],[Coronary Artery Disease]
6,NCT03386435,The Effect of Remote Ischemic Preconditioning ...,The Effect of Remote Ischemic Preconditioning ...,COMPLETED,INTERVENTIONAL,[NA],"[Tissue Donors, Liver Transplantation, Ischemi..."
7,NCT05541835,Hematological Abnormalities in Children,Hematological Abnormalities In Children With C...,UNKNOWN,OBSERVATIONAL,None,[Hematologic Diseases]
8,NCT05665335,A Post-Market Study in Greece of a Minimally I...,A Post-Market Study of a Minimally Invasive Be...,COMPLETED,INTERVENTIONAL,[NA],[Breast Ptosis]
9,NCT02260635,A Study of Evacetrapib (LY2484595) in Japanese...,A Double-Blind Efficacy and Safety Study of Ev...,TERMINATED,INTERVENTIONAL,[PHASE3],[Hypercholesterolemia]

In [58]:
df_studies.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   nct_id          10 non-null     str
 1   brief_title     10 non-null     str
 2   official_title  10 non-null     str
 3   overall_status  10 non-null     str
 4   study_type      10 non-null     str
 5   phases          8 non-null      object
 6   conditions      10 non-null     object
dtypes: object(2), str(5)
memory usage: 692.0+ bytes

In [60]:
df_study_conditions = (
    df_studies[["nct_id", "conditions"]]
    .explode("conditions")
    .rename(columns={"conditions": "condition_name"})
    .dropna()
    .reset_index(drop=True)
)
df_study_conditions

         nct_id                                    condition_name
0   NCT00830635                                     Breast Cancer
1   NCT00830635                                        Depression
2   NCT00830635             Long-term Effects of Cancer Treatment
3   NCT00830635                                   Prostate Cancer
4   NCT00830635  Psychosocial Effects of Cancer and Its Treatment
5   NCT06798935                              Rectovaginal Fistula
6   NCT06798935                                Anovaginal Fistula
7   NCT01990235                                   Chronic Disease
8   NCT01419535                                 Endocrine Disease
9   NCT01419535                                          Diabetes
10  NCT05944835                                           Surgery
11  NCT05470335                           Coronary Artery Disease
12  NCT03386435                                     Tissue Donors
13  NCT03386435                             Liver Transplantation
14  NCT03386435                       Ischemia Reperfusion Injury
15  NCT05541835                              Hematologic Diseases
16  NCT05665335                                     Breast Ptosis
17  NCT02260635                              Hypercholesterolemia

### Data Quality checks

In [62]:
df_studies.isna().sum()

nct_id            0
brief_title       0
official_title    0
overall_status    0
study_type        0
phases            2
conditions        0
dtype: int64

In [64]:
df_studies["nct_id"].duplicated().sum()

np.int64(0)

In [65]:
df_studies["overall_status"].value_counts(dropna=False)

overall_status
COMPLETED     6
UNKNOWN       2
RECRUITING    1
TERMINATED    1
Name: count, dtype: int64

In [66]:
df_studies["study_type"].value_counts(dropna=False)

study_type
INTERVENTIONAL    8
OBSERVATIONAL     2
Name: count, dtype: int64